name: ActionBarMessager
main: io.github.rothes.actionbarmessager.bukkit.ActionBarMessager
version: ${projectVersionString}
author: Rothes
api-version: 1.13
depend:
  - ProtocolLib
  - PlaceholderAPI
commands:
  actionbarmessager:
    description: Main commands.
    aliases:
      - abm
permissions:
  'actionbarmessager.command.toggle':
    description: Allow you to toggle reciving status.
    default: true
  'actionbarmessager.command.reload':
    description: Allow you to reload the plugin.
    default: op