name: ActionBarMessager Snapshot Builder

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew shadowJar
        
#       - uses: actions/upload-artifact@v3
#         with:
#           name: ActionBarMessager-Snapshot
#           path: target/ActionBarMessager v[\d\.]+.jar
      
      - run: mkdir ActionBarMessager && cp build/libs/*.jar ActionBarMessager
      
      - uses: actions/upload-artifact@v3
        with:
          name: ActionBarMessager-Snapshot
          path: ActionBarMessager
